# Generated by Django 5.1.6 on 2025-02-18 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_publisherregister_user_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publisherregister',
            name='user',
        ),
    ]
