# Generated by Django 5.1.6 on 2025-02-18 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_publisherregister_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Event',
            new_name='eventtickets',
        ),
    ]
