# Generated by Django 5.1.6 on 2025-03-28 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_adminnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisherregister',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
