# Generated by Django 5.2 on 2025-04-16 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_publisherregister_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtickets',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
